#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#
# Standard Gradle wrapper. Requires gradle/wrapper/gradle-wrapper.jar, which
# Android Studio downloads automatically on first project sync. If building from
# the command line without it, run:  gradle wrapper --gradle-version 8.9
#

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
